### ISSUE TITLE
Do I need an Apple Developer ID to compile and run this program?

### ISSUE THREAD

**Issue by jamesmortensen** [KhaosT/MacVM#11]
I upgraded my operating system to Mac OS Monterey v12.0.1 and also updated Xcode to v13.1.  While the compile errors I was facing before have all been resolved, I'm now faced with these errors about the signing certificate and developer account.

Do I need to pay for a developer account with Apple?  I'm just wanting to compile this and run it and try it out.  Thank you.

<img width="532" alt="Screenshot 2021-11-01 at 11 38 18 AM" src="https://user-images.githubusercontent.com/1315816/139628986-c52834b7-c72d-4ec2-acc6-72a087f88a1a.png">

<img width="1140" alt="Screenshot 2021-11-01 at 11 38 07 AM" src="https://user-images.githubusercontent.com/1315816/139628977-c4c7119b-a21b-492d-9846-8c0ca6331d46.png">

**Comment by KhaosT** [comment]
You don’t need to have a paid Apple developer account. You should be able to modify the signing settings to build to run locally without an account.

**Comment by jamesmortensen** [comment]
<img width="865" alt="Screenshot 2021-11-01 at 11 50 23 AM" src="https://user-images.githubusercontent.com/1315816/139630151-429d948b-434c-4a90-910d-12d2afe843b1.png">

I changed the "Signing (Debug" settings so that the option "Sign to Run Locally" is selected, and now I can build and run.  Hope this helps others!
