### ISSUE TITLE
What is the file picker dialog for? What am I supposed to select after running the project?

### ISSUE THREAD

**Issue by jamesmortensen** [KhaosT/MacVM#12]
When I run the project in XCode, a file picker dialog pops up.  Can someone please tell me what am I supposed to select at this point?  

I'm running XCode 13 on macOS 12.0.1 Monterey.  

I did get a Monterey VM created using [Ming's repository here](https://github.com/ming900518/macOS-Virtual-Machine), which is based on Khaos's work, and thanks to [Mr. Macintosh's walkthrough of Ming's instructions](https://youtu.be/XxkzuFejjj0), but I want to give it a try with Khaos's original solution as well.

I should also add I'm on an ARM64 Mac M1.

**Comment by jamesmortensen** [comment]
If it helps, this is what I'm seeing when running the project:

<img width="1440" alt="Screenshot 2021-11-06 at 7 41 27 PM" src="https://user-images.githubusercontent.com/1315816/140612695-19d6bbdd-35da-45e8-9b7a-904c1712fd4b.png">

Sorry if this is something super simple I'm doing wrong, but I'm pretty much new to Xcode/Swift and Apple Development.

**Comment by GJoshi27** [comment]
You need to click on New Document button on file picker dialog, and it should continue for you.

**Comment by jamesmortensen** [comment]
Thanks @GJoshi27 that was what I was missing!
