### ISSUE TITLE
App Beeps when Attempting to Type

### ISSUE THREAD

**Issue by ajacocks** [KhaosT/MacVM#13]
I've got an odd issue; after building on 12.0.1 in Xcode 13.1, the install of UniversalMac_12.0.1_21A559_Restore.ipsw goes fine, until I need to type. While the mouse works perfectly, I get a beep with every keystroke, and nothing appears on the screen.

**Comment by 123marvin123** [comment]
Same problem here, same restore file and Xcode version. I can use the mouse but not the keyboard, so we can't actually finish the installation process since we can't enter a username and password for creating a local user account.

**Comment by mcnahum** [comment]
I got that issue too. copy a word from the T&C before and use it as user/ password.
At the end of the setup assistant, reboot and it will be ok

**Comment by KhaosT** [comment]
There is a bug with how SwiftUI forward keystrokes. The easiest workaround in this case would be close the app and reopen it, then the keyboard should work.

**Comment by ajacocks** [comment]
yeah, I noticed that, as well. Thanks!
