### ISSUE TITLE
How to disable SIP

### ISSUE THREAD

**Issue by Count-Count** [KhaosT/MacVM#15]
I haven't found a way to get the VM into recovery mode so that I can disable SIP. Anyone any idea?

BTW: Great work and thank you, @KhaosT!!!

**Comment by KhaosT** [comment]
There is no public way to do this. In order to boot into recoveryOS, you'll need to invoke the private API to pass in the special configuration at the boot time.

Here are the API headers I found. https://gist.github.com/KhaosT/8167170d1452daec1ba292e37e5768c8

**Comment by Count-Count** [comment]
Works great, thanks!

**Comment by mcnahum** [comment]
Any chance to have a button added on the UI to boot from recovery?

**Comment by jankais3r** [comment]
> Works great, thanks!

Hi, could you please elaborate how you managed to boot into Recovery in MacVM to disable SIP?
