### ISSUE TITLE
Trying to use MacVM with Monterey Beta 3 getting "unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by jamesdbailey** [KhaosT/MacVM#2]
On Monterey Beta 3. When I try to install after setting the IPSW file I get:

-[VZMacOSInstaller initWithVirtualMachine:restoreImage:]: unrecognized selector sent to instance

VMInstance line 125.

Seems odd since the Swift to Obj-C bridge seems to be there. Not too expert at Swift though.

**Comment by aaronraimist** [comment]
It looks like this API changed in beta 3

**Comment by MrBenFTW** [comment]
It is a simple fix.

see my PR: #4

**Comment by jamesdbailey** [comment]
I'm dumb. I was still using the previous version of Xcode. No wonder I couldn't find the correct API.
