### ISSUE TITLE
Graphics Issue - Chrome

### ISSUE THREAD

**Issue by nodeGarden** [KhaosT/MacVM#20]
Has anyone had an issue with Menu's and Hover States not working? Basically the area affected just blanks out. This is most notable in Chrome, making it nearly unusable. 
![image](https://user-images.githubusercontent.com/253262/146227453-e25de50c-ac9b-4907-bb1a-dc0c816c7a2c.png)

Safari works pretty well so far. Sadly, we use a set of custom chrome extensions for daily work, so switching to Safari isn't an option right now.

**Comment by randompasser** [comment]
Trying launching Chrome with GPU acceleration disabled and see if that fixes your issue:

https://gist.github.com/bangonkali/be61ab880c890c17cb3d

**Comment by nodeGarden** [comment]
> Trying launching Chrome with GPU acceleration disabled and see if that fixes your issue:
> 
> https://gist.github.com/bangonkali/be61ab880c890c17cb3d

This did the trick. 
![image](https://user-images.githubusercontent.com/253262/146387057-8774e668-a243-4155-8861-6c625ea372df.png)

Ironically, the toggle wasn't clickable because it kept blanking out for the same reason 🙄  But with some zooming in/out I was able to click fast enough.
