### ISSUE TITLE
No signing certificate for team ID '7C2EXSD3YV'

### ISSUE THREAD

**Issue by magnusviri** [KhaosT/MacVM#22]
I get these 2 errors when I try to build the project:

"There are no accounts registered with Xcode. Add your developer account to Xcode"

and

"No signing certificate 'Mac Development' found: No 'Mac Development' signing certificate matching team ID '7C2EXSD3YV' with a private key was found."

If I edit MacVM.xcodeproj/project.pbxproj and change the 2 instances of "DEVELOPMENT_TEAM = 7C2EXSD3YV;" to 'DEVELOPMENT_TEAM = "";' then it builds and runs without error.

**Comment by John-K** [comment]
I've found this to be a common problem in Xcode projects on GitHub.

If anyone has advice on how to fix this, PRs are welcome

**Comment by KhaosT** [comment]
Alright I updated the project to use ad-hoc sign so it's no longer associated with a team.

<img width="552" alt="Screen Shot 2022-01-06 at 10 00 31 AM" src="https://user-images.githubusercontent.com/1725664/148429129-477ef89d-e87b-41bb-93b9-37c87f0cf91a.png">
