### ISSUE TITLE
Removing unneeded software to reduce the size of the VM

### ISSUE THREAD

**Issue by jamesmortensen** [KhaosT/MacVM#27]
First, thanks again for putting this project together.  I'm wondering if there are ways to reduce the size of the VM by removing unneeded or unwanted software?

The smallest usable sized VM I was able to create was about 30GB.  This didn't leave a lot of room to install other tools.  However, macOS comes with all kinds of software by default which is not needed.  If I could delete GarageBand, Keynote, Pages, and Numbers, that would save approximately 3GB in disk size.  

I learned that these programs are kept on a different partition on a read-only drive.  The only way I have thought to remove them is to disable the system integrity protection via the recovery partition.  However, on Mac M1 computers, this requires powering down the machine and holding the power button until the options menu appears.   I'm not sure how to do this on a VM since the VM has no physical keyboard with a power button.

Is there any known way or other ideas for creating macOS virtual machines that have a smaller disk footprint?  We won't necessarily need every piece of software if we're just looking to test a specific product.  Thank you again!

**Comment by KhaosT** [comment]
iWork and GarageBand are not bundled with the OS (they are installed on retail machine). For VM created with IPSW, you don't have iWork and GarageBand taking up space.
