### ISSUE TITLE
Failed to install after the IPSW file selection and also run when multiple display are connected

### ISSUE THREAD

**Issue by rluvaton** [KhaosT/MacVM#29]
When my 2 monitors are connected and my laptop lid is closed (probably even when it's not) I can't press install and no error is shown this is also happening when I trying to start the VM

I found out in the Console app, the error was
```
Error: Error Domain=VZErrorDomain Code=2 "More than one display is configured." UserInfo={NSLocalizedFailure=Invalid virtual machine configuration., NSLocalizedFailureReason=More than one display is configured.}
``` 

I plugged the 2nd external screen and pressed install and return it and it worked

**Comment by John-K** [comment]
Is this still an issue after #26 was merged?

**Comment by rluvaton** [comment]
> Is this still an issue after #26 was merged?

Yes

**Comment by yzgyyang** [comment]
Still an issue

**Comment by John-K** [comment]
So laptop screen + 1 external screen results in everything working, but laptop screen + 2 external screens results in a silent error?

**Comment by ryanbooker** [comment]
Laptop + 1 screen gives the error.

**Comment by KhaosT** [comment]
This is resolved.
