### ISSUE TITLE
Hide title bar

### ISSUE THREAD

**Issue by lo3w3n** [KhaosT/MacVM#30]
Hi. How do you hide the window title in full screen?

**Comment by franklefebvre** [comment]
Hi,
I made the modification in my fork (along with another modification to allow to change RAM & CPU settings after the VM has been created).
@KhaosT I can submit a PR if you are interested. Or feel free to grab whatever you want from my repository.

**Comment by lo3w3n** [comment]
Yes, please submit PR

**Comment by franklefebvre** [comment]
PR submitted.

**Comment by KhaosT** [comment]
This is merged ^^
