### ISSUE TITLE
macOS Ventura VM Support

### ISSUE THREAD

**Issue by moyitpro** [KhaosT/MacVM#34]
I have a developer account and wanted to try to create a VM with the macOS Ventura support with the ipsw. It doesn't seem to do anything as the install process is stuck at 0%.

Also noticed that nothing is written to the image file either.

0+0 records in
0+0 records out
0 bytes transferred in 0.000006 secs (0 bytes/sec)

Is it because I'm running macOS Monterey and creating and running a Ventura VM requires me to also run the same OS? I don't want to do that since of compatibility issues and I kind of want to try to run it in a VM first. Anyone experiencing the same issue?

**Comment by fkorotkov** [comment]
You need to recompile and use Xcode 14 Beta. At least that helped in my case.

**Comment by moyitpro** [comment]
> You need to recompile and use Xcode 14 Beta. At least that helped in my case.
![2022-06-06_21-17-03](https://user-images.githubusercontent.com/161183/172275811-a7348cb6-425f-4b35-bb01-3072496e7953.jpg)

It appeared that this did the trick as the VM managed to create after recompiling it with Xcode 14.
