### ISSUE TITLE
macOS Big Sur (ARM) Support

### ISSUE THREAD

**Issue by AlejandroVolkova** [KhaosT/MacVM#49]
This is not an issue, but rather a question: why is there no alternative to virtualizing macOS Big Sur on M-Series machines? I've seen that even Parallels cannot virtualize operative systems under Monterrey; why isn't it possible when this is an arm-based system?

**Comment by KhaosT** [comment]
All macOS virtualization solutions on Apple silicon uses [the framework](https://developer.apple.com/documentation/virtualization) provided by Apple, and that thing requires special support from the OS image to run, which only exists on Monterey and later.
