### ISSUE TITLE
Is it possible to sign-in to Apple ID in VM?

### ISSUE THREAD

**Issue by bdruth** [KhaosT/MacVM#9]
Getting the "Verification failed" error when trying to sign-in an Apple ID, which I _think_ is required to install Rosetta 2? It's certainly required to grab anything out of the Mac App Store or install updates, I believe.

**Comment by jamesmortensen** [comment]
@bdruth I didn't try signing into the App Store, but if Rosetta 2 is what you need, this article,  [Installing Rosetta 2 on Apple Silicon Macs](https://derflounder.wordpress.com/2020/11/17/installing-rosetta-2-on-apple-silicon-macs/) has instructions for how to install without the App Store.  Basically, you just need to run the following terminal command:

```
$ /usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

Afterwards, I installed the Intel version of Visual Studio Code, and it launches.  So I assume Rosetta 2 is installed.

**Comment by bdruth** [comment]
I'll try it again, but this failed for me originally, too.

**Comment by bdruth** [comment]
Worked, thx!

**Comment by Dirk23** [comment]
Same here, cant log into Apple ID or Appstore or iMessage

**Comment by Mcrich23** [comment]
Can't either

**Comment by mcnahum** [comment]
I got that too now .. but I guess it's new with the last version of macOS
...

**Comment by matthewruzzi** [comment]
This seems to be a limitation of the Virtualization framework. 
https://kb.parallels.com/128867
https://forum.parallels.com/threads/apple-id-login-in-macos-guest-os.355059/
https://developer.apple.com/forums/thread/707682

**Comment by ZM71** [comment]
how to log in bypassing the verification failed or unknown error occurred problem in macOS 15 (Sequoia) in VMware?

**Comment by bdruth** [comment]
@ZM71 this isn't a GitHub repo that supports VMware Fusion. 

Apple ID/iCloud sign-in is a new feature of macOS 15 - it seems to only work for iCloud, generally - does not support App Store, which still fails. Both the host machine and the guest machine need to be macOS 15, furthermore, the guest needs to be a newly-installed VM, created on a macOS 15 host. The guest VM cannot be upgraded from an earlier version of macOS to enable this new capability, as the new feature is enabled in the Virtualization framework at the time that the VM is _created_.

I haven't used `KhaosT/MacVM` in awhile, but I just tried this in UTM and it works as expected, using the most recent version of UTM as of this writing. I imagine it should work similarly for VMware Fusion, but I can't confirm that.

**Comment by ZM71** [comment]
@bdruth how do i log in creating a new machine in 17 free?

**Comment by ZM71** [comment]
what do you mean both the host need macOS what is the point of the vm then?

**Comment by bdruth** [comment]
@ZM71 - this isn't a support forum for VMWare, sorry. You're posting on an issue in a GitHub repo for a completely different virtualization product. 

RE: your 2nd question - it is against Apple's license terms & conditions to run VMs of macOS on non-Mac hardware. Vendors of virtualization software (e.g. Broadcom/VMware, Parallels, Oracle Virtualbox, etc.) will observe this restriction and not permit you to create a macOS VM on non-Mac hardware. That might defeat the point for _you_, but for the broader community, it is still quite useful (I can run a macOS VM via proxmox or esxi virtualization on an Intel Mac mini, for instance). Many folks use VMs locally, as well, in order to isolate their host machine from needing to run certain things (e.g. captive VPNs, etc.). Either way, you're posting on an issue re: the macOS Virtualization framework, which is built-in to macOS, so ... you kinda need to be running *on* macOS to be able to use this framework (it's for hosting the guest).

**Comment by ZM71** [comment]
what do you mean whatever programme it is i'm sure it is the same patch for it and yes VMware does not care the system itself works but not apple id and i don't care if it is against apple terms they cannot stop me. i wrote about my problem. do not try to convince me to buy real cause i wont. not for VMware what is it then he clearly uses something like VMware for this then it must be the same solution for this. -_-

**Comment by ZM71** [comment]
what is utm even more shit needed for this machine?

**Comment by bdruth** [comment]
Sorry you continue to have difficulty @ZM71

**Comment by ZM71** [comment]
idk how to fix this maybe it is just too complicated with your solutions. i found something with the config and clover tool making some numbers and you put them at the right lines at you can sign into appstore etc.

**Comment by AI1120** [comment]
I have installed macOS Tahoe using VMware Workstation Pro 25H2 and encountered an issue when attempting to sign in to my Apple ID: "Verification failed. An unknown error occurred."
How can I resolve this issue?

**Comment by wkddudwo** [comment]
Here's a video explaining how to fix the error "Verification failed. An unknown error occurred." I'm sure you've all figured it out already, but I'm linking it for those who haven't.
https://www.youtube.com/watch?v=5Tj9U_sKWkc&t=1085s
